// <auto-generated />
using System;
using AuthenticationAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthenticationAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthenticationAPI.Database.ConfirmationCodes", b =>
                {
                    b.Property<byte[]>("Email")
                        .HasColumnType("bytea");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CodeLifetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Delay")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Email");

                    b.ToTable("confirmation_codes");
                });

            modelBuilder.Entity("AuthenticationAPI.Database.SessionTokens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SessionLifetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SessionToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("session_tokens");
                });

            modelBuilder.Entity("AuthenticationAPI.Database.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("TwoStepLogin")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Username")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UsernameNormalized")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
